language: ruby
sudo: false
dist: trusty
cache: bundler
before_install:
  # For testing purposes:
  - git config --global user.email "samuel@oriontransfer.net"
  - git config --global user.name "Samuel Williams"
  # https://github.com/rubygems/rubygems/issues/1448
  - gem update --system
rvm:
  - 2.2
  - 2.3
  - 2.4
  - jruby-head
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
